### ISSUE TITLE
Config.yml 어떻게 하죠?

### ISSUE THREAD

**Issue by MangoCubes** [HmHmmHm/EmailAuth#1]
제가 님 플러그인 중 EmailAuth 를 찾아서 다운받아 쓸려고 하는데 config.yml 에 조금 이해가 안가는 부분이 있어서 물어보고 싶습니다. 우선 config.yml 이 있으면:
# -----------------------------------------------------
# The server name is displayed in the e-mail

serverName: "PocketMine"
# Title to be displayed in the email

subjectName: "[PocketMine] 메일이 도착했습니다"
# Email Encoding

encoding: euc-kr 
영어는 euc-en 인가요?
# -----------------------------------------------------
# EMAIL-LOGIN SETTINGS
# -----------------------------------------------------
# E-mail address of the administrator

adminEmail: "" 
# E-mail hostDomain of the administrator

adminEmailHost: "" 이거 궁금해요... 이 이메일을 쓰는데 google.com 인가요, 아님 gmail.com 인가요?
# E-mail Port of the administrator

adminEmailPort: "" 이거 진짜 모르겠음
# E-mail password of the administrator

adminEmailPassword: "" 제 이메일 비밀번호?! ㅋ
# -----------------------------------------------------
# AUTH SETTINGS
# -----------------------------------------------------

원래 여기 세팅 다 SimpleAuth 랑 연관 없는거죠? 디펜던트 없는거 보니까
# Minimum password length

minPasswordLength: 5
# Sign up disabled

disableRegister: false
# Default Server Prefix

default-prefix: "[ 서버 ]"
# Time to wait for authentication

authenticateTimeout: 60
# -----------------------------------------------------
# CUSTOMPACKET SETTINGS
# -----------------------------------------------------

이 세팅 다 뭐에요???? ㅠㅠ
# Whether using a custom packet
# type : null || true || false

usecustompacket: null
# Set servermode
# type : null || master || slave

servermode: null

passcode: null
masterip: null
masterport: null
# -----------------------------------------------------

네... 좀 물어보는게 많아서 죄송합니다. 제가 여기에 물어보고 싶은 곳에 댓글 처럼 달았는데 알려주셧으면 감사합니다.
그리고 라이센스를 읽어보았는데 (제가 제대로 이해했다면) 코드를 마음껏 변경 못한다고 하던데, 맞나요? 된다면 허락 좀..ㅋ SimpleAuthHelper 같은 기능을 넣었으면 합니다.
읽어주셔서 감사합니다.
흠흐으으으으음흠

**Comment by HmHmmHm** [comment]
이거 아직 개발중이라 좀 기다리셔야해영
아마 제 생각인데 UUIDAuth 프로젝트에
EmailAuth 가 합쳐지는 결과로 나올 듯합니다.
